### ISSUE TITLE
update logo

### ISSUE THREAD

**Issue by neila** [unchain-tech/website#1]
@mashharuki [参照ロゴデータ](https://github.com/unchain-tech/website/tree/main/public)の更新をお願いします.

- [x] favicon
- [x] [Header 左](https://github.com/unchain-tech/website/blob/main/src/components/molecules/header/index.tsx#L13)
- [x] [ページ下部](https://github.com/unchain-tech/website/blob/main/src/components/sections/joinus/index.tsx#L39)

**Comment by mashharuki** [comment]
https://github.com/unchain-tech/website/pull/2

@neila  新しいロゴデータを追加してプルリク出しました！

**Comment by mashharuki** [comment]
<img width="1709" alt="スクリーンショット 2024-05-15 20 44 52" src="https://github.com/unchain-tech/website/assets/44923695/a1092b96-81ac-42e3-a051-5bb751715e0e">
<img width="1709" alt="スクリーンショット 2024-05-15 20 44 45" src="https://github.com/unchain-tech/website/assets/44923695/e3386f5b-a671-4500-8ef7-60d5ebf0c980">
<img width="245" alt="スクリーンショット 2024-05-15 20 44 58" src="https://github.com/unchain-tech/website/assets/44923695/e4cd7f27-1a71-4222-98e9-bec7bf25ff87">

**Comment by mashharuki** [comment]
↑ 更新しました！！

**Comment by mashharuki** [comment]
対応したのでクローズします！！
